server:
  port: ${APP_SERVICE_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: telegram-app
  data:
    mongodb:
      uri: ${MONGODB_URI:uri}
      database: ${MONGODB_DATABASE:app-telegram-db}

telegram:
  bot:
    username: ${TELEGRAM.BOT.USERNAME:bot_name}
    token: ${TELEGRAM.BOT.TOKEN:app_token}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    path: /api/documentation

jwt:
  app:
    secret: ${JWT_SECRET_KEY:jwt_key}