###
GET http://localhost:8080/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.p15kV_CF0i5Hg15tuhwyakfSkBFWYs108QU7IJUXwSY

###
GET http://localhost:8080/v1/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.p15kV_CF0i5Hg15tuhwyakfSkBFWYs108QU7IJUXwSY

###
POST http://localhost:8080/v1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.p15kV_CF0i5Hg15tuhwyakfSkBFWYs108QU7IJUXwSY

{
  "catId": -1001600823930,
  "message": "New post \n https://www.eurointegration.com.ua/news/2024/02/19/7179946/"
}