###
GET http://localhost:8081/v1/users

###
GET http://localhost:8081/v1/chats

###
POST http://localhost:8081/v1/messages
Content-Type: application/json

{
  "catId": 1138276555,
  "message": "New post \n https://www.eurointegration.com.ua/news/2024/02/19/7179946/"
}